TAXONOMY = [
    {
        "id": "inside",
        "kind": "location",
        "title": "Inside the cabin",
        "subtitle": "HVAC, cluster, windows, airbags, rattles, smells",
        "icon": "cabin",
        "sortOrder": 1,
    },
    {
        "id": "outside",
        "kind": "location",
        "title": "Outside the body",
        "subtitle": "Lights, rust, leaks on paint, water ingress",
        "icon": "body",
        "sortOrder": 2,
    },
    {
        "id": "engine-bay",
        "kind": "location",
        "title": "Engine bay / motor",
        "subtitle": "Noise, leaks, belts, 48V generator, turbo, cooling",
        "icon": "engine",
        "sortOrder": 3,
    },
    {
        "id": "front",
        "kind": "location",
        "title": "Front end",
        "subtitle": "Radiator, condenser, steering, front brakes",
        "icon": "front",
        "sortOrder": 4,
    },
    {
        "id": "rear",
        "kind": "location",
        "title": "Rear, tray and tailgate",
        "subtitle": "Leaf springs, diff, exhaust, DPF, door drains",
        "icon": "rear",
        "sortOrder": 5,
    },
    {
        "id": "under",
        "kind": "location",
        "title": "Undercarriage",
        "subtitle": "Driveshafts, fuel lines, oil, exhaust blow",
        "icon": "under",
        "sortOrder": 6,
    },
    {
        "id": "wheels",
        "kind": "location",
        "title": "Wheels and tyres",
        "subtitle": "Bearings, CV boots, uneven wear, pull",
        "icon": "wheels",
        "sortOrder": 7,
    },
    {
        "id": "electrical",
        "kind": "location",
        "title": "Electrical 12V and 48V",
        "subtitle": "Batteries, DC-DC, charging, drain, lamps",
        "icon": "electrical",
        "sortOrder": 8,
    },
    {
        "id": "glass",
        "kind": "location",
        "title": "Glass and windscreen",
        "subtitle": "Leaks, wipers, smear, cracked screen",
        "icon": "glass",
        "sortOrder": 9,
    },
    {
        "id": "sound",
        "kind": "sense",
        "title": "Sound",
        "subtitle": "Knock, tick, squeal, grind, hiss, rattle, boom",
        "icon": "sound",
        "sortOrder": 1,
    },
    {
        "id": "look",
        "kind": "sense",
        "title": "Look",
        "subtitle": "Smoke colour, leak colour, lamps, rust, belt glaze",
        "icon": "look",
        "sortOrder": 2,
    },
    {
        "id": "leak",
        "kind": "sense",
        "title": "Fluid leak",
        "subtitle": "Colour, smell, then the circuit that lost level",
        "icon": "leak",
        "sortOrder": 6,
    },
    {
        "id": "performance",
        "kind": "sense",
        "title": "Performance",
        "subtitle": "Limp, no boost, heat, fuel use, vibration, shift",
        "icon": "performance",
        "sortOrder": 3,
    },
    {
        "id": "smell",
        "kind": "sense",
        "title": "Smell",
        "subtitle": "Coolant, fuel, clutch, electrical",
        "icon": "smell",
        "sortOrder": 4,
    },
    {
        "id": "feel",
        "kind": "sense",
        "title": "Feel",
        "subtitle": "Pedal, steering kick, idle shake, shudder",
        "icon": "feel",
        "sortOrder": 5,
    },
    {
        "id": "engine-mechanical",
        "kind": "system",
        "title": "Engine mechanical",
        "subtitle": "Bottom end, valvetrain, timing, pistons",
        "icon": "engine",
        "sortOrder": 1,
    },
    {
        "id": "fuel",
        "kind": "system",
        "title": "Fuel and injection",
        "subtitle": "Rail, injectors, fifth injector, filters",
        "icon": "fuel",
        "sortOrder": 2,
    },
    {
        "id": "air-turbo",
        "kind": "system",
        "title": "Air and turbo",
        "subtitle": "Intercooler, actuator, boost leaks, airbox",
        "icon": "engine",
        "sortOrder": 3,
    },
    {
        "id": "exhaust-dpf",
        "kind": "system",
        "title": "Exhaust, DPF and SCR",
        "subtitle": "Regen, soot, AdBlue, fifth injector",
        "icon": "exhaust",
        "sortOrder": 4,
    },
    {
        "id": "cooling",
        "kind": "system",
        "title": "Cooling",
        "subtitle": "Thermostat, fans, EGR cooler, radiator",
        "icon": "cooling",
        "sortOrder": 5,
    },
    {
        "id": "lubrication",
        "kind": "system",
        "title": "Lubrication",
        "subtitle": "Dilution, leaks, oil in turbo",
        "icon": "engine",
        "sortOrder": 6,
    },
    {
        "id": "drivetrain",
        "kind": "system",
        "title": "Drivetrain",
        "subtitle": "Clutch, auto, transfer, diffs, 4WD",
        "icon": "drivetrain",
        "sortOrder": 7,
    },
    {
        "id": "brakes",
        "kind": "system",
        "title": "Brakes",
        "subtitle": "Pads, rotors, fluid, ABS",
        "icon": "brakes",
        "sortOrder": 8,
    },
    {
        "id": "steering-suspension",
        "kind": "system",
        "title": "Steering and suspension",
        "subtitle": "Rack, bushes, leaf springs, alignment",
        "icon": "front",
        "sortOrder": 9,
    },
    {
        "id": "hvac",
        "kind": "system",
        "title": "HVAC",
        "subtitle": "Compressor, blend doors, odour",
        "icon": "cabin",
        "sortOrder": 10,
    },
    {
        "id": "body-electrical",
        "kind": "system",
        "title": "Body electrical",
        "subtitle": "Windows, lamps, drains, cluster",
        "icon": "electrical",
        "sortOrder": 11,
    },
    {
        "id": "mhev-48v",
        "kind": "system",
        "title": "48V V-Active / MHEV",
        "subtitle": "Pack, BSG, DC-DC, belt, 12V interaction",
        "icon": "hybrid",
        "sortOrder": 12,
    },
]
