MAKES = [
    {"id": "toyota", "name": "Toyota"},
    {"id": "ford", "name": "Ford"},
    {"id": "isuzu", "name": "Isuzu"},
    {"id": "mitsubishi", "name": "Mitsubishi"},
    {"id": "mazda", "name": "Mazda"},
    {"id": "nissan", "name": "Nissan"},
    {"id": "volkswagen", "name": "Volkswagen"},
    {"id": "hyundai", "name": "Hyundai"},
    {"id": "kia", "name": "Kia"},
    {"id": "subaru", "name": "Subaru"},
    {"id": "honda", "name": "Honda"},
    {"id": "mercedes", "name": "Mercedes-Benz"},
    {"id": "bmw", "name": "BMW"},
    {"id": "audi", "name": "Audi"},
    {"id": "mg", "name": "MG"},
]

MODELS = [
    {"id": "hilux", "makeId": "toyota", "name": "Hilux", "bodyType": "ute"},
    {"id": "prado", "makeId": "toyota", "name": "LandCruiser Prado", "bodyType": "suv"},
    {"id": "landcruiser", "makeId": "toyota", "name": "LandCruiser", "bodyType": "suv"},
    {"id": "rav4", "makeId": "toyota", "name": "RAV4", "bodyType": "suv"},
    {"id": "corolla", "makeId": "toyota", "name": "Corolla", "bodyType": "car"},
    {"id": "camry", "makeId": "toyota", "name": "Camry", "bodyType": "car"},
    {"id": "kluger", "makeId": "toyota", "name": "Kluger", "bodyType": "suv"},
    {"id": "hiace", "makeId": "toyota", "name": "HiAce", "bodyType": "van"},
    {"id": "ranger", "makeId": "ford", "name": "Ranger", "bodyType": "ute"},
    {"id": "everest", "makeId": "ford", "name": "Everest", "bodyType": "suv"},
    {"id": "dmax", "makeId": "isuzu", "name": "D-Max", "bodyType": "ute"},
    {"id": "triton", "makeId": "mitsubishi", "name": "Triton", "bodyType": "ute"},
    {"id": "outlander", "makeId": "mitsubishi", "name": "Outlander", "bodyType": "suv"},
    {"id": "pajero-sport", "makeId": "mitsubishi", "name": "Pajero Sport", "bodyType": "suv"},
    {"id": "bt50", "makeId": "mazda", "name": "BT-50", "bodyType": "ute"},
    {"id": "cx5", "makeId": "mazda", "name": "CX-5", "bodyType": "suv"},
    {"id": "navara", "makeId": "nissan", "name": "Navara", "bodyType": "ute"},
    {"id": "xtrail", "makeId": "nissan", "name": "X-Trail", "bodyType": "suv"},
    {"id": "amarok", "makeId": "volkswagen", "name": "Amarok", "bodyType": "ute"},
    {"id": "golf", "makeId": "volkswagen", "name": "Golf", "bodyType": "car"},
    {"id": "tiguan", "makeId": "volkswagen", "name": "Tiguan", "bodyType": "suv"},
    {"id": "tucson", "makeId": "hyundai", "name": "Tucson", "bodyType": "suv"},
    {"id": "i30", "makeId": "hyundai", "name": "i30", "bodyType": "car"},
    {"id": "santa-fe", "makeId": "hyundai", "name": "Santa Fe", "bodyType": "suv"},
    {"id": "sportage", "makeId": "kia", "name": "Sportage", "bodyType": "suv"},
    {"id": "carnival", "makeId": "kia", "name": "Carnival", "bodyType": "van"},
    {"id": "forester", "makeId": "subaru", "name": "Forester", "bodyType": "suv"},
    {"id": "outback", "makeId": "subaru", "name": "Outback", "bodyType": "wagon"},
    {"id": "crv", "makeId": "honda", "name": "CR-V", "bodyType": "suv"},
    {"id": "civic", "makeId": "honda", "name": "Civic", "bodyType": "car"},
    {"id": "c-class", "makeId": "mercedes", "name": "C-Class", "bodyType": "car"},
    {"id": "e-class", "makeId": "mercedes", "name": "E-Class", "bodyType": "car"},
    {"id": "glc", "makeId": "mercedes", "name": "GLC", "bodyType": "suv"},
    {"id": "gle", "makeId": "mercedes", "name": "GLE", "bodyType": "suv"},
    {"id": "3-series", "makeId": "bmw", "name": "3 Series", "bodyType": "car"},
    {"id": "5-series", "makeId": "bmw", "name": "5 Series", "bodyType": "car"},
    {"id": "x5", "makeId": "bmw", "name": "X5", "bodyType": "suv"},
    {"id": "a4", "makeId": "audi", "name": "A4", "bodyType": "car"},
    {"id": "a5", "makeId": "audi", "name": "A5", "bodyType": "car"},
    {"id": "q5", "makeId": "audi", "name": "Q5", "bodyType": "suv"},
    {"id": "q7", "makeId": "audi", "name": "Q7", "bodyType": "suv"},
    {"id": "zs", "makeId": "mg", "name": "ZS", "bodyType": "suv"},
    {"id": "hs", "makeId": "mg", "name": "HS", "bodyType": "suv"},
]

GENERATIONS = [
    {"id": "hilux-n50", "modelId": "hilux", "code": "N50", "name": "N50", "yearFrom": 1997, "yearTo": 2004},
    {"id": "hilux-n70", "modelId": "hilux", "code": "N70", "name": "N70", "yearFrom": 2005, "yearTo": 2015},
    {"id": "hilux-n80", "modelId": "hilux", "code": "N80", "name": "N80", "yearFrom": 2015, "yearTo": 2025},
    {"id": "hilux-n80-48v", "modelId": "hilux", "code": "N80-VActive", "name": "N80 V-Active 48V", "yearFrom": 2024, "yearTo": None},
    {"id": "prado-150", "modelId": "prado", "code": "150", "name": "150 Series", "yearFrom": 2009, "yearTo": 2023},
    {"id": "prado-250", "modelId": "prado", "code": "250", "name": "250 Series", "yearFrom": 2024, "yearTo": None},
    {"id": "lc-70", "modelId": "landcruiser", "code": "70", "name": "70 Series", "yearFrom": 2007, "yearTo": None},
    {"id": "lc-200", "modelId": "landcruiser", "code": "200", "name": "200 Series", "yearFrom": 2007, "yearTo": 2021},
    {"id": "lc-300", "modelId": "landcruiser", "code": "300", "name": "300 Series", "yearFrom": 2021, "yearTo": None},
    {"id": "rav4-xa50", "modelId": "rav4", "code": "XA50", "name": "XA50", "yearFrom": 2019, "yearTo": None},
    {"id": "corolla-e210", "modelId": "corolla", "code": "E210", "name": "E210", "yearFrom": 2018, "yearTo": None},
    {"id": "camry-xv70", "modelId": "camry", "code": "XV70", "name": "XV70", "yearFrom": 2017, "yearTo": None},
    {"id": "kluger-xu70", "modelId": "kluger", "code": "XU70", "name": "XU70", "yearFrom": 2021, "yearTo": None},
    {"id": "hiace-h300", "modelId": "hiace", "code": "H300", "name": "H300", "yearFrom": 2019, "yearTo": None},
    {"id": "ranger-px", "modelId": "ranger", "code": "PX", "name": "PX / PX2 / PX3", "yearFrom": 2011, "yearTo": 2022},
    {"id": "ranger-p703", "modelId": "ranger", "code": "P703", "name": "Next-Gen P703", "yearFrom": 2022, "yearTo": None},
    {"id": "everest-ua", "modelId": "everest", "code": "UA", "name": "UA / UA II", "yearFrom": 2015, "yearTo": 2022},
    {"id": "everest-ub", "modelId": "everest", "code": "UB", "name": "Next-Gen", "yearFrom": 2022, "yearTo": None},
    {"id": "dmax-rt", "modelId": "dmax", "code": "RT", "name": "RT / RG", "yearFrom": 2012, "yearTo": 2020},
    {"id": "dmax-rg", "modelId": "dmax", "code": "RG3", "name": "RG III", "yearFrom": 2020, "yearTo": None},
    {"id": "triton-mq", "modelId": "triton", "code": "MQ", "name": "MQ / MR", "yearFrom": 2015, "yearTo": 2023},
    {"id": "triton-mv", "modelId": "triton", "code": "MV", "name": "MV", "yearFrom": 2024, "yearTo": None},
    {"id": "outlander-gf", "modelId": "outlander", "code": "GF", "name": "GF / GG", "yearFrom": 2012, "yearTo": 2021},
    {"id": "outlander-gm", "modelId": "outlander", "code": "GM", "name": "GM", "yearFrom": 2021, "yearTo": None},
    {"id": "pajero-sport-qe", "modelId": "pajero-sport", "code": "QE", "name": "QE / QF", "yearFrom": 2015, "yearTo": None},
    {"id": "bt50-up", "modelId": "bt50", "code": "UP", "name": "UP / UR", "yearFrom": 2011, "yearTo": 2020},
    {"id": "bt50-tf", "modelId": "bt50", "code": "TF", "name": "TF", "yearFrom": 2020, "yearTo": None},
    {"id": "cx5-kf", "modelId": "cx5", "code": "KF", "name": "KF", "yearFrom": 2017, "yearTo": None},
    {"id": "navara-d23", "modelId": "navara", "code": "D23", "name": "D23 NP300", "yearFrom": 2015, "yearTo": None},
    {"id": "xtrail-t33", "modelId": "xtrail", "code": "T33", "name": "T33", "yearFrom": 2022, "yearTo": None},
    {"id": "amarok-2h", "modelId": "amarok", "code": "2H", "name": "2H", "yearFrom": 2010, "yearTo": 2022},
    {"id": "amarok-nf", "modelId": "amarok", "code": "NF", "name": "NF", "yearFrom": 2023, "yearTo": None},
    {"id": "golf-mk7", "modelId": "golf", "code": "MK7", "name": "Mk7 / 7.5", "yearFrom": 2013, "yearTo": 2020},
    {"id": "golf-mk8", "modelId": "golf", "code": "MK8", "name": "Mk8", "yearFrom": 2021, "yearTo": None},
    {"id": "tiguan-ad", "modelId": "tiguan", "code": "AD", "name": "AD / 5N", "yearFrom": 2016, "yearTo": None},
    {"id": "tucson-tl", "modelId": "tucson", "code": "TL", "name": "TL", "yearFrom": 2015, "yearTo": 2020},
    {"id": "tucson-nx", "modelId": "tucson", "code": "NX", "name": "NX", "yearFrom": 2021, "yearTo": None},
    {"id": "i30-pd", "modelId": "i30", "code": "PD", "name": "PD", "yearFrom": 2017, "yearTo": None},
    {"id": "santa-fe-tm", "modelId": "santa-fe", "code": "TM", "name": "TM / MX5", "yearFrom": 2018, "yearTo": None},
    {"id": "sportage-ql", "modelId": "sportage", "code": "QL", "name": "QL / NQ5", "yearFrom": 2015, "yearTo": None},
    {"id": "carnival-ka4", "modelId": "carnival", "code": "KA4", "name": "KA4", "yearFrom": 2020, "yearTo": None},
    {"id": "forester-sk", "modelId": "forester", "code": "SK", "name": "SK", "yearFrom": 2018, "yearTo": None},
    {"id": "outback-bt", "modelId": "outback", "code": "BT", "name": "BT", "yearFrom": 2021, "yearTo": None},
    {"id": "crv-rw", "modelId": "crv", "code": "RW", "name": "RW / RS", "yearFrom": 2017, "yearTo": None},
    {"id": "civic-fk", "modelId": "civic", "code": "FK", "name": "10th / 11th", "yearFrom": 2016, "yearTo": None},
    {"id": "c-class-w206", "modelId": "c-class", "code": "W206", "name": "W206", "yearFrom": 2021, "yearTo": None},
    {"id": "e-class-w214", "modelId": "e-class", "code": "W214", "name": "W214", "yearFrom": 2023, "yearTo": None},
    {"id": "glc-x254", "modelId": "glc", "code": "X254", "name": "X254", "yearFrom": 2022, "yearTo": None},
    {"id": "gle-v167", "modelId": "gle", "code": "V167", "name": "V167", "yearFrom": 2019, "yearTo": None},
    {"id": "3-g20", "modelId": "3-series", "code": "G20", "name": "G20", "yearFrom": 2019, "yearTo": None},
    {"id": "5-g60", "modelId": "5-series", "code": "G60", "name": "G60", "yearFrom": 2023, "yearTo": None},
    {"id": "x5-g05", "modelId": "x5", "code": "G05", "name": "G05", "yearFrom": 2018, "yearTo": None},
    {"id": "a4-b9", "modelId": "a4", "code": "B9", "name": "B9", "yearFrom": 2016, "yearTo": 2024},
    {"id": "a5-b10", "modelId": "a5", "code": "B10", "name": "B10", "yearFrom": 2024, "yearTo": None},
    {"id": "q5-fy", "modelId": "q5", "code": "FY", "name": "FY", "yearFrom": 2017, "yearTo": None},
    {"id": "q7-4m", "modelId": "q7", "code": "4M", "name": "4M", "yearFrom": 2015, "yearTo": None},
    {"id": "zs-1", "modelId": "zs", "code": "ZS", "name": "ZS", "yearFrom": 2018, "yearTo": None},
    {"id": "hs-1", "modelId": "hs", "code": "HS", "name": "HS", "yearFrom": 2019, "yearTo": None},
]

ENGINES = [
    {"id": "1kd-ftv", "code": "1KD-FTV", "fuel": "diesel", "displacementL": "3.0", "notes": "N70 D4D. Timing belt. Injector seats and oil dilution risk."},
    {"id": "2kd-ftv", "code": "2KD-FTV", "fuel": "diesel", "displacementL": "2.5", "notes": "N70 / N50 late 2.5 D4D."},
    {"id": "2tr-fe", "code": "2TR-FE", "fuel": "petrol", "displacementL": "2.7", "notes": "Workmate petrol."},
    {"id": "1gr-fe", "code": "1GR-FE", "fuel": "petrol", "displacementL": "4.0", "notes": "N70 V6."},
    {"id": "5l-e", "code": "5L-E", "fuel": "diesel", "displacementL": "3.0", "notes": "N50 naturally aspirated diesel."},
    {"id": "1gd-ftv", "code": "1GD-FTV", "fuel": "diesel", "displacementL": "2.8", "notes": "N80 2.8. Early DPF and fifth injector issues."},
    {"id": "2gd-ftv", "code": "2GD-FTV", "fuel": "diesel", "displacementL": "2.4", "notes": "Lower output GD diesel."},
    {"id": "1vd-ftv", "code": "1VD-FTV", "fuel": "diesel", "displacementL": "4.5", "notes": "70/200 V8 diesel."},
    {"id": "f33a-ftv", "code": "F33A-FTV", "fuel": "diesel", "displacementL": "3.3", "notes": "300 Series twin turbo V6 diesel."},
    {"id": "a25a-fxs", "code": "A25A-FXS", "fuel": "hybrid", "displacementL": "2.5", "notes": "Toyota full hybrid, not 48V."},
    {"id": "2zr-fxe", "code": "2ZR-FXE", "fuel": "hybrid", "displacementL": "1.8", "notes": "Corolla hybrid."},
    {"id": "1gd-hiace", "code": "1GD-FTV", "fuel": "diesel", "displacementL": "2.8", "notes": "HiAce 2.8 diesel."},
    {"id": "p5at", "code": "P5AT", "fuel": "diesel", "displacementL": "3.2", "notes": "Ranger PX 3.2 five cylinder."},
    {"id": "yn2s", "code": "YN2S", "fuel": "diesel", "displacementL": "2.2", "notes": "Ranger PX 2.2."},
    {"id": "bi-turbo-20", "code": "Y20", "fuel": "diesel", "displacementL": "2.0", "notes": "Ranger/Everest 2.0 bi-turbo."},
    {"id": "v6-30-ford", "code": "V6-3.0", "fuel": "diesel", "displacementL": "3.0", "notes": "Next-Gen Ranger/Everest V6."},
    {"id": "4jj1", "code": "4JJ1", "fuel": "diesel", "displacementL": "3.0", "notes": "Isuzu 3.0 common rail."},
    {"id": "4n15", "code": "4N15", "fuel": "diesel", "displacementL": "2.4", "notes": "Triton MQ/MR."},
    {"id": "4n16", "code": "4N16", "fuel": "diesel", "displacementL": "2.4", "notes": "Triton MV."},
    {"id": "4n14", "code": "4N14", "fuel": "petrol", "displacementL": "2.4", "notes": "Outlander / related petrol."},
    {"id": "phev-outlander", "code": "PHEV", "fuel": "phev", "displacementL": "2.4", "notes": "Outlander PHEV high voltage, not 48V."},
    {"id": "ys23", "code": "YS23DDT", "fuel": "diesel", "displacementL": "2.3", "notes": "Navara NP300."},
    {"id": "t9-40", "code": "T9", "fuel": "diesel", "displacementL": "3.0", "notes": "Amarok V6 3.0."},
    {"id": "ea888", "code": "EA888", "fuel": "petrol", "displacementL": "2.0", "notes": "VW / Golf TSI."},
    {"id": "eatsi-48v", "code": "eTSI-48V", "fuel": "mhev", "displacementL": "1.5", "notes": "VW 48V mild hybrid where sold."},
    {"id": "g4kj", "code": "G4KJ", "fuel": "petrol", "displacementL": "2.4", "notes": "Hyundai/Kia GDI."},
    {"id": "smartstream-16t", "code": "1.6T", "fuel": "hybrid", "displacementL": "1.6", "notes": "Tucson/Sportage hybrid."},
    {"id": "fb25", "code": "FB25", "fuel": "petrol", "displacementL": "2.5", "notes": "Subaru boxer."},
    {"id": "k20c", "code": "K20C", "fuel": "petrol", "displacementL": "2.0", "notes": "Honda turbo."},
    {"id": "m254-48v", "code": "M254", "fuel": "mhev", "displacementL": "2.0", "notes": "Mercedes EQ Boost 48V."},
    {"id": "b48-48v", "code": "B48", "fuel": "mhev", "displacementL": "2.0", "notes": "BMW 48V mild hybrid."},
    {"id": "b57-48v", "code": "B57", "fuel": "mhev", "displacementL": "3.0", "notes": "BMW 48V diesel."},
    {"id": "ea888-mhev", "code": "TFSI-MHEV", "fuel": "mhev", "displacementL": "2.0", "notes": "Audi 48V mild hybrid."},
    {"id": "ea839-mhev", "code": "V6-MHEV", "fuel": "mhev", "displacementL": "3.0", "notes": "Audi V6 48V."},
    {"id": "mg-15t", "code": "15T", "fuel": "petrol", "displacementL": "1.5", "notes": "MG turbo petrol."},
]


def _v(generation, engine, drivetrain="4x4", is48v=False, voltage=None):
    suffix = "48v" if is48v else "12v"
    return {
        "id": f"{generation}-{engine}-{suffix}-{drivetrain}",
        "generationId": generation,
        "engineId": engine,
        "drivetrain": drivetrain,
        "is48v": is48v,
        "voltageLabel": voltage,
    }


VARIANTS = [
    _v("hilux-n50", "5l-e"),
    _v("hilux-n50", "2kd-ftv"),
    _v("hilux-n70", "1kd-ftv"),
    _v("hilux-n70", "2kd-ftv"),
    _v("hilux-n70", "2tr-fe", "4x2"),
    _v("hilux-n70", "1gr-fe"),
    _v("hilux-n80", "1gd-ftv"),
    _v("hilux-n80", "2gd-ftv"),
    _v("hilux-n80", "2tr-fe", "4x2"),
    _v("hilux-n80-48v", "1gd-ftv", is48v=True, voltage="V-Active 48V"),
    _v("prado-150", "1kd-ftv"),
    _v("prado-150", "1gd-ftv"),
    _v("prado-250", "1gd-ftv"),
    _v("lc-70", "1vd-ftv"),
    _v("lc-200", "1vd-ftv"),
    _v("lc-300", "f33a-ftv"),
    _v("rav4-xa50", "a25a-fxs"),
    _v("corolla-e210", "2zr-fxe"),
    _v("camry-xv70", "a25a-fxs"),
    _v("kluger-xu70", "a25a-fxs"),
    _v("hiace-h300", "1gd-hiace"),
    _v("ranger-px", "p5at"),
    _v("ranger-px", "yn2s"),
    _v("ranger-px", "bi-turbo-20"),
    _v("ranger-p703", "bi-turbo-20"),
    _v("ranger-p703", "v6-30-ford"),
    _v("everest-ua", "p5at"),
    _v("everest-ua", "bi-turbo-20"),
    _v("everest-ub", "bi-turbo-20"),
    _v("everest-ub", "v6-30-ford"),
    _v("dmax-rt", "4jj1"),
    _v("dmax-rg", "4jj1"),
    _v("triton-mq", "4n15"),
    _v("triton-mv", "4n16"),
    _v("outlander-gf", "4n14"),
    _v("outlander-gm", "phev-outlander"),
    _v("pajero-sport-qe", "4n15"),
    _v("bt50-up", "p5at"),
    _v("bt50-tf", "4jj1"),
    _v("cx5-kf", "g4kj"),
    _v("navara-d23", "ys23"),
    _v("xtrail-t33", "k20c"),
    _v("amarok-2h", "t9-40"),
    _v("amarok-nf", "v6-30-ford"),
    _v("golf-mk7", "ea888"),
    _v("golf-mk8", "eatsi-48v", "fwd", True, "eTSI 48V"),
    _v("tiguan-ad", "ea888"),
    _v("tucson-tl", "g4kj"),
    _v("tucson-nx", "smartstream-16t"),
    _v("i30-pd", "g4kj"),
    _v("santa-fe-tm", "smartstream-16t"),
    _v("sportage-ql", "g4kj"),
    _v("carnival-ka4", "smartstream-16t"),
    _v("forester-sk", "fb25"),
    _v("outback-bt", "fb25"),
    _v("crv-rw", "k20c"),
    _v("civic-fk", "k20c"),
    _v("c-class-w206", "m254-48v", "rwd", True, "EQ Boost 48V"),
    _v("e-class-w214", "m254-48v", "rwd", True, "EQ Boost 48V"),
    _v("glc-x254", "m254-48v", "awd", True, "EQ Boost 48V"),
    _v("gle-v167", "m254-48v", "awd", True, "EQ Boost 48V"),
    _v("3-g20", "b48-48v", "rwd", True, "BMW 48V"),
    _v("5-g60", "b57-48v", "awd", True, "BMW 48V"),
    _v("x5-g05", "b57-48v", "awd", True, "BMW 48V"),
    _v("a4-b9", "ea888-mhev", "awd", True, "Audi MHEV 48V"),
    _v("a5-b10", "ea888-mhev", "awd", True, "Mild hybrid plus 48V"),
    _v("q5-fy", "ea888-mhev", "awd", True, "Audi MHEV 48V"),
    _v("q7-4m", "ea839-mhev", "awd", True, "Audi MHEV 48V"),
    _v("zs-1", "mg-15t", "fwd"),
    _v("hs-1", "mg-15t", "fwd"),
]
